import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useNavigation } from '@react-navigation/native';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useLayoutEffect, useState } from 'react';
import { Alert, Linking, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';

import { useAppColors } from '@/lib/app-theme';
import { formatCurrency, formatSignedCurrency } from '@/lib/currency-format';
import { formatDateTimeDMY } from '@/lib/date-format';
import { getEarlyCashOuts, getResults, getSessionMeta } from '@/lib/firestore';
import { computeSettlements } from '@/lib/settlement';
import type { EarlyCashOut, SessionResult } from '@/types';

export default function SessionSummaryScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const navigation = useNavigation();
  const c = useAppColors();
  const [results, setResults] = useState<SessionResult[]>([]);
  const [earlyCashOuts, setEarlyCashOuts] = useState<EarlyCashOut[]>([]);
  const [sessionDate, setSessionDate] = useState<Date | undefined>();
  const [sessionFinishedAt, setSessionFinishedAt] = useState<Date | undefined>();
  const [sessionLocation, setSessionLocation] = useState<string | undefined>();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    (async () => {
      try {
        const [data, early, meta] = await Promise.all([
          getResults(id),
          getEarlyCashOuts(id),
          getSessionMeta(id),
        ]);
        setResults(data.sort((a, b) => b.profit - a.profit));
        setEarlyCashOuts(early);
        setSessionDate(meta.date);
        setSessionFinishedAt(meta.finishedAt);
        setSessionLocation(meta.location);
      } catch (e) {
        Alert.alert('Error', e instanceof Error ? e.message : 'Failed to load results.');
      } finally {
        setLoading(false);
      }
    })();
  }, [id]);

  const earlyPlayerIds = new Set(earlyCashOuts.map((ec) => ec.playerId));

  const settlements = computeSettlements(results);
  const durationMs =
    sessionDate && sessionFinishedAt
      ? Math.max(0, sessionFinishedAt.getTime() - sessionDate.getTime())
      : 0;
  const durationText = (() => {
    if (!durationMs) return 'N/A';
    const totalMinutes = Math.floor(durationMs / 60000);
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    return hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;
  })();

  const buildSettlementMessage = useCallback((): string => {
    const title = sessionDate
      ? `Nonsense - ${formatDateTimeDMY(sessionDate)}`
      : 'Nonsense Session Summary';
    const lines: string[] = [title];
    lines.push(`Location: ${sessionLocation?.trim() ? sessionLocation.trim() : 'N/A'}`);
    lines.push(`Duration: ${durationText}`);
    lines.push('', 'Results:');

    for (const item of results) {
      lines.push(
        `- ${item.playerName}: In ${formatCurrency(item.totalBuyIn)}, Out ${formatCurrency(item.cashOut)}, P/L ${formatSignedCurrency(item.profit)}`
      );
    }

    if (settlements.length > 0) {
      lines.push('', 'Settlement:');
      for (const s of settlements) {
        lines.push(`- ${s.from} pays ${s.to} ${formatCurrency(s.amount)}`);
      }
    } else {
      lines.push('', 'Settlement: No payments needed.');
    }

    lines.push('', 'Generated by Nonsense');
    return lines.join('\n');
  }, [durationText, results, sessionDate, sessionLocation, settlements]);

  const handleShareWhatsApp = useCallback(async () => {
    const message = buildSettlementMessage();
    try {
      const url = `whatsapp://send?text=${encodeURIComponent(message)}`;
      const canOpen = await Linking.canOpenURL(url);
      if (canOpen) {
        await Linking.openURL(url);
        return;
      }
      await Share.share({ message });
    } catch (e) {
      Alert.alert('Share failed', e instanceof Error ? e.message : 'Could not open share options.');
    }
  }, [buildSettlementMessage]);

  useLayoutEffect(() => {
    navigation.setOptions({
      title: sessionDate ? formatDateTimeDMY(sessionDate) : 'Session Summary',
      headerRight: () => (
        <Pressable
          onPress={handleShareWhatsApp}
          style={styles.headerShareBtn}
          accessibilityRole="button"
          accessibilityLabel="Share on WhatsApp">
          <MaterialCommunityIcons name="whatsapp" size={16} color="#fff" />
        </Pressable>
      ),
    });
  }, [navigation, sessionDate, handleShareWhatsApp]);

  if (loading) {
    return (
      <View style={[styles.screen, { backgroundColor: c.bg }]}>
        <Text style={{ color: c.textMuted }}>Loading...</Text>
      </View>
    );
  }

  if (results.length === 0) {
    return (
      <View style={[styles.screen, { backgroundColor: c.bg }]}>
        <Text style={{ color: c.textMuted }}>No results found. Complete cash-out first.</Text>
        <Pressable style={[styles.button, { backgroundColor: c.accent }]} onPress={() => router.back()}>
          <Text style={styles.buttonLabel}>Go Back</Text>
        </Pressable>
      </View>
    );
  }

  return (
    <ScrollView
      style={[styles.screen, { backgroundColor: c.bg }]}
      contentContainerStyle={styles.scrollContent}
      keyboardShouldPersistTaps="handled">
      <View style={[styles.metaCard, { backgroundColor: c.card, borderColor: c.border }]}>
        <View style={styles.metaRow}>
          <View style={styles.metaCol}>
            <Text style={[styles.metaLabel, { color: c.textMuted }]}>Location</Text>
            <Text style={[styles.metaValue, { color: c.text }]} numberOfLines={2}>
              {sessionLocation?.trim() ? sessionLocation.trim() : 'N/A'}
            </Text>
          </View>
          <View style={styles.metaCol}>
            <Text style={[styles.metaLabel, { color: c.textMuted }]}>Duration</Text>
            <Text style={[styles.metaValue, { color: c.text }]}>{durationText}</Text>
          </View>
        </View>
      </View>

      <View style={styles.resultsBlock}>
        <Text style={[styles.sectionTitle, { color: c.text }]}>Results</Text>
        {results.map((item, index) => (
          <View
            key={item.playerId}
            style={[
              styles.resultRow,
              { backgroundColor: c.card, borderColor: c.border },
            ]}>
            <View style={styles.resultLeft}>
              <Text style={[styles.rank, { color: c.textMuted }]}>#{index + 1}</Text>
              <Text style={[styles.resultName, { color: c.text }]}>{item.playerName}</Text>
              {earlyPlayerIds.has(item.playerId) && (
                <View style={[styles.earlyBadge, { backgroundColor: c.badge.cashedOut }]}>
                  <Text style={styles.earlyBadgeText}>EARLY</Text>
                </View>
              )}
            </View>
            <View style={styles.resultRight}>
              <Text style={[styles.resultDetail, { color: c.textMuted }]}>
                In: {formatCurrency(item.totalBuyIn)}  Out: {formatCurrency(item.cashOut)}
              </Text>
              <Text
                style={[
                  styles.resultProfit,
                  { color: item.profit >= 0 ? c.profit : c.loss },
                ]}>
                {formatSignedCurrency(item.profit)}
              </Text>
            </View>
          </View>
        ))}
      </View>

      {settlements.length > 0 ? (
        <View style={styles.settlementBlock}>
          <Text style={[styles.sectionTitle, { color: c.text }]}>Settlement</Text>
          <View
            style={[
              styles.settlementCard,
              { backgroundColor: c.card, borderColor: c.border },
            ]}>
            {settlements.map((s, i) => (
              <View key={i} style={styles.settlementRow}>
                <Text style={{ color: c.chipValueText }}>
                  {s.from} pays {s.to}
                </Text>
                <Text style={[styles.settlementAmount, { color: c.warning }]}>
                  {formatCurrency(s.amount)}
                </Text>
              </View>
            ))}
          </View>
        </View>
      ) : null}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 16,
    paddingTop: 12,
    gap: 10,
    paddingBottom: 32,
  },
  /** Keeps Results + rows grouped; Settlement always follows this block in document order. */
  resultsBlock: {
    gap: 10,
  },
  settlementBlock: {
    gap: 10,
  },
  sectionTitle: {
    fontWeight: '700',
    fontSize: 15,
    marginTop: 6,
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
    marginBottom: 6,
  },
  resultLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rank: {
    fontWeight: '700',
    fontSize: 13,
    width: 24,
  },
  resultName: {
    fontWeight: '600',
  },
  earlyBadge: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  earlyBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  resultRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  resultDetail: {
    fontSize: 11,
  },
  resultProfit: {
    fontWeight: '700',
    fontSize: 15,
  },
  settlementCard: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
    gap: 8,
  },
  settlementRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settlementAmount: {
    fontWeight: '700',
  },
  headerShareBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#25D366',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metaCard: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metaCol: {
    flex: 1,
  },
  metaLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  metaValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  button: {
    marginTop: 'auto',
    borderRadius: 8,
    alignItems: 'center',
    paddingVertical: 12,
  },
  buttonLabel: {
    color: '#fff',
    fontWeight: '700',
  },
});
